version: 0.2

# 참고 https://jojoldu.tistory.com/282#recentEntries
#env:
#  variables:
#    CURRENT: date +"%Y%m%d%H%M%S"

phases:
  install:
    commands:
      - echo "install start at $(date +"%Y-%m-%d %H:%M:%S")"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - ln -s /usr/local/aws-cli/v2/2.0.8/bin/aws /usr/bin/aws
      - aws --version
  build:
    commands:
      - export CURRENT=$(date +"%Y%m%d%H%M%S")
      - echo "build time tag is $CURRENT"
      - echo "boot jar build start at $(date +"%Y-%m-%d %H:%M:%S")"
      - chmod +x ./gradlew
      - ./gradlew bootJar
#      - ./gradlew build
      - echo "docker images build start at $(date +"%Y-%m-%d %H:%M:%S")"
      - echo "$(docker --version)"
      - docker build -t msa.example:$CURRENT .
      - echo "build end"
  post_build:
    commands:
      - echo "post build start"
      - echo "bootJar -> $(ls -al ./build/libs/)"
      - echo "docker images -> $(docker images)"
      - echo "post build end"
      - aws --version

cache:
  paths:
    - '/root/.gradle/caches/**/*'