version: 0.2

# 참고 https://jojoldu.tistory.com/282#recentEntries
#env:
#  variables:
#    DIV:

phases:
  install:
    commands:
      - export DIV="=================================================="
      - echo $DIV
      - echo "install start at $(date +"%Y-%m-%d %H:%M:%S")"
      - echo $DIV
      - echo "install aws cli v2 at $(date +"%Y-%m-%d %H:%M:%S")"
      - echo $DIV
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - echo $(/usr/local/bin/aws --version)
      - echo $DIV
      - echo "setting aws config file at $(date +"%Y-%m-%d %H:%M:%S")"
      - mkdir ~/.aws
      - echo "[default]" >> ~./aws/credentials
      - echo "aws_access_key_id = $AWS_KEY_ID" >> ~./aws/credentials
      - echo "aws_secret_access_key = $AWS_KEY_VALUE" >> ~./aws/credentials
      - echo "region = ap-northeast-2" >> ~./aws/credentials
      - cat ~./aws/credentials
  build:
    commands:
      - export CURRENT=$(date +"%Y%m%d%H%M%S")
      - echo "build time tag is $CURRENT"
      - echo "boot jar build start at $(date +"%Y-%m-%d %H:%M:%S")"
#      - chmod +x ./gradlew
#      - ./gradlew bootJar
#      - echo "docker images build start at $(date +"%Y-%m-%d %H:%M:%S")"
#      - echo "$(docker --version)"
#      - docker build -t msa.example:$CURRENT .
#      - echo "build end"
  post_build:
    commands:
      - echo "post build start"
      - /usr/local/bin/aws ecr get-login-password --region ap-northeast-2
#      - echo "bootJar -> $(ls -al ./build/libs/)"
#      - echo "docker images -> $(docker images)"
      - echo "post build end"

cache:
  paths:
    - '/root/.gradle/caches/**/*'