version: 0.2

phases:
  build:
    commands:
      - echo "hello, aws codebuild"
      - echo "phases - build"
      - chmod +x ./gradlew
      - ./gradlew bootJar
      - echo "$(docker --version)"
      - docker build -t msa.example:0.1 .
  post_build:
    commands:
      - echo "bootJar -> $(ls -al ./build/libs/)"
      - echo "docker images -> $(docker images)"