version: 0.2

env:
  variables:
    CURRENT: date +"%Y%m%d%H%M%S"

phases:
  build:
    commands:
      - echo "build start"
      - echo "phases - build"
      - chmod +x ./gradlew
      - echo $CURRENT
#      - ./gradlew bootJar
#      - ./gradlew build
#      - echo "$(docker --version)"
#      - docker build -t msa.example:$CURRENT .
      - echo "build end"
  post_build:
    commands:
      - echo "post build start"
#      - echo "bootJar -> $(ls -al ./build/libs/)"
#      - echo "docker images -> $(docker images)"
      - echo "post build end"