version: 0.2

phases:
  build:
    commands:
      - echo "hello, aws codebuild"
      - echo "phases - build"
      - chmod +x ./gradlew
      - ./gradlew bootJar
      - echo "$(docker --version)"
  post_build:
    commands:
      - echo "$(ls -al ./build/libs/)"