version: 0.2

# 참고 https://jojoldu.tistory.com/282#recentEntries
#env:
#  variables:
#    DIV:

phases:
  install:
    commands:
      - export DIV="==================================================\n"
      - printf $DIV"INSTALL PHASE START AT $(date +"%Y-%m-%d %H:%M:%S")"
      - printf $DIV"INSTALL AWS CLI V2 START AT $(date +"%Y-%m-%d %H:%M:%S")"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - echo $(/usr/local/bin/aws --version)
#      - echo $DIV
#      - echo "setting aws config file at $(date +"%Y-%m-%d %H:%M:%S")"
#      - export AWS_CONFIG_PATH=~/.aws
#      - export AWS_CONFIG_CREDENTIALS=credentials
#      - export AWS_CONFIG_CONFIG=config
#      - mkdir $AWS_CONFIG_PATH
#      - echo "[default]" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CREDENTIALS
#      - echo "aws_access_key_id = $AWS_KEY_ID" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CREDENTIALS
#      - echo "aws_secret_access_key = $AWS_KEY_VALUE" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CREDENTIALS
#      - echo "[default]" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CONFIG
#      - echo "region = ap-northeast-2" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CONFIG
#      - cat $AWS_CONFIG_PATH/$AWS_CONFIG_CREDENTIALS
#      - cat $AWS_CONFIG_PATH/$AWS_CONFIG_CONFIG
  build:
    commands:
      - export CURRENT_TAG=$(date +"%Y%m%d%H%M%S")
      - printf $DIV"BUILD PHASE START AT $(date +"%Y-%m-%d %H:%M:%S")"
      - printf $DIV"BUILD TIMESTAMP IS $CURRENT_TAG"
      - printf $DIV"BOOT JAR BUILD START AT $(date +"%Y-%m-%d %H:%M:%S")"
#      - chmod +x ./gradlew
#      - ./gradlew bootJar
#      - echo "docker images build start at $(date +"%Y-%m-%d %H:%M:%S")"
#      - echo "$(docker --version)"
#      - docker build -t msa.example:$CURRENT_TAG .
#      - echo "build end"
  post_build:
    commands:
      - export MSA_EXAMPLE_DOCKER_REPOSITORY=081582853021.dkr.ecr.ap-northeast-2.amazonaws.com
      - printf $DIV"POST BUILD PHASE START AT $(date +"%Y-%m-%d %H:%M:%S")"
      - /usr/local/bin/aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $MSA_EXAMPLE_DOCKER_REPOSITORY/msa.example
      - printf $DIV"bootJar -> $(ls -al ./build/libs/)"
      - printf $DIV"docker images -> $(docker images)"

cache:
  paths:
    - '/root/.gradle/caches/**/*'