server:
  port: 8090

spring:
  datasource:
    hikari:
      maximum-pool-size: 4

mybatis:
   # typehandler - https://mybatis.org/mybatis-3/ko/configuration.html#typeHandlers
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com/harm/app/mapper/**/*.xml
  type-aliases-package: com.harm.app.dto.model

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

logging:
  level:
    root: DEBUG
    com: DEBUG
#    org:
#      springframework:
#        context:
#          annotation: TRACE
